language: ruby
rvm:
- 2.5
before_script:
- bin/rails db:create
- bin/rails db:migrate
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: LX14EuGM+/stZxnxCXW/gcTuaAMFhNwWB+tXTJq+arT8a2FCEvbjVBZI4jbG39AU03Ww1VuDpvpTLj34TYVI/Kf3aPPjf1iKg8TCVDcCfifO6VIZP0CTwkEX1+bzgInbP07HGrKpNmuupj/In5jqhMff7QMC8BACEK2icmEabqKI/iPo8ed52fAkrfvvc8Fvzg2xPVbP//wtpxzhLzgqc6nSgv5eb2Fz89niRqkHsMHhUV3Sq3L3DlfyqTBbp2XaZVmZd/DjWndjHI1Cewu++kWwBkml+/7p0iPMrujhz/L6uBc3/MiSADbxzb2N0NlpX4n1lSEESuXJ4TM4PxDLkOLInlNJQSFcaHca7tJAHbdIy6FDZhfnDbNjkA2TbtNBTP+7Eli4g0ypVFJUIuUNvWgzVkpIP0araGnjVay+ylAXG2iFAciQ2Z1IF0/ikuinTbSixzbGfRk/7WFkibY5gc3HTGyo097US4/7eaHz4sPaSeywJ9tVqMMEt3mNDvOxVrpQjUBrMFemoUaJz9dkQZ4+SfAwmRMOD3hrKvbnUOJ7wlZSlRzsVIaqWuVHZyOyARtJrLqg/FCtRA+ypr2z+bUvIuQNMhKHy+A7svwSMvpi2QKbCl3L+e2pLDSq3HhQv1zdlKrW6505s5aZkOSQLpltvzp6qLg8XsmWOcxHv7s=
  app: acebook-roku
  run: 
    - bin/rails db:create
    - bin/rails db:migrate
